# Generated by Django 4.2.6 on 2023-10-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookShoppe', '0003_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-default,1-Trending'),
        ),
    ]
