# Generated by Django 4.2.6 on 2023-10-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookShoppe', '0004_book_quantity_book_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='book_qty',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
